---
title: "`r params$doc_title`"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    css: "style.css"
    includes:
      after_body: footer.html
    
params:
  temporada : "2022-II"
  temporada_2 : "2021-II"
  color_esfuerzo : "tomato1" # purple3 tomato4royalblue1
  color_esfuerzo_2 : "royalblue1" # royalblue1 tomato4
  color_cpue : "tomato1" #'black' 'darkslategray4' darkorange2
  color_cpue_2 : "royalblue1" #'black' 'darkslategray4'
  color_indicadores : "chartreuse4" #'maroon' 'blue2' 'yellow4' 'darkgoldenrod1' 'steelblue1'
  color_indicadores_2 : "blue2" #'maroon' 'blue2' 'yellow4' 'darkgoldenrod1' 'steelblue1'
  paso_dias : 3
  marker_size : 10
  legend_size : 16
  areas : TRUE
  n_decimales : 2
  carpeta_indicadores : "H:/.shortcut-targets-by-id/1Y-zd3BCw35q05RN7fix9Vo7fdH8mFpmu/DATOS/INDICADORES/diarios"
  carpeta_trayectorias : "H:/.shortcut-targets-by-id/1Y-zd3BCw35q05RN7fix9Vo7fdH8mFpmu/DATOS/TRAYECTORIAS/"
  carpeta_calas : "H:/.shortcut-targets-by-id/1Y-zd3BCw35q05RN7fix9Vo7fdH8mFpmu/DATOS/CALAS/"
  doc_title : "Reporte - II Temporada de Pesca 2022 - NC"

---


```{r setup, include=FALSE}

require(flexdashboard)
require(tidyverse)
require(plotly)
require(DT)

### Temporadas

temporada_1 = load(file = file.path(params$carpeta_indicadores,paste0(params$temporada,".RData")))

current_temp = get(temporada_1)

rownames(current_temp) = NULL


if(!is.null(params$temporada_2)){
  
  temporada_2 = load(file = file.path(params$carpeta_indicadores,paste0(params$temporada_2,".RData")))

  current_temp_2 = get(temporada_2)
  
  rownames(current_temp_2) = NULL

}


### Calas


calas_1 = load(file = file.path(params$carpeta_calas,paste0(params$temporada,".RData")))

current_calas = get(calas_1)

rownames(current_calas) = NULL

### Trayectorias


trayectorias_1 = load(file = file.path(params$carpeta_trayectorias,paste0(params$temporada,".RData")))

current_trayectorias = get(trayectorias_1)

rownames(current_trayectorias) = NULL


```



# Plot Diarios{data-orientation=columns data-navmenu="DESEMBARQUES"}

Rows
-------------------------------------

###
```{r, fig.width=4, fig.height=5}


current_temp %>% 
  plot_ly(x = ~fecha) %>%
  add_trace(y = ~captura,
            type = 'bar', 
            color = I('dodgerblue'), 
            name = paste0("Desembarques (t)"), 
            yaxis = "y",
            marker = list(opacity = 0.5)) %>%
  add_trace(y = ~viajes, 
            type = 'scatter',
            mode = 'lines+markers', 
            color = I('black'), 
            name = paste0("Viajes"), 
            yaxis='y2', 
            marker = list(size = params$marker_size, opacity = 0.5), 
            line  = list(opacity = 0.5)) %>%
  layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(current_temp$fecha, na.rm = TRUE)-1,max(current_temp$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Desembarques (t)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(current_temp$captura, na.rm = TRUE)*1.4)
  ),
    yaxis2 = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Viajes", font = list(size = 20)),
      overlaying = "y", 
      side = "right",
      ticks = "outside", 
      range = c(0, max(current_temp$viajes, na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(size = params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)'),

      margin = list(
        l = 100,
        r = 100,
        b = 50,
        t = 50
  )
)



```


###
```{r, fig.width=4, fig.height=5}


desembarques_fabricas = current_temp %>% 
  dplyr::select(fecha, captura_AUSTRAL, captura_CAPRICORNIO, captura_CENTINELA, captura_CFG, captura_DIAMANTE, captura_EXALMAR, captura_HAYDUK, captura_TASA) %>% 
  dplyr::mutate(dia = 1:n()) %>% 
  pivot_longer(., cols = 2:9, names_to = c("empresa"), values_to = "catch_1") %>%
  mutate(id = gsub("captura_", "",empresa))


desembarques_fabricas %>%
   mutate(across(where(is.numeric), ~na_if(., 0))) %>% arrange(fecha) %>% 
  plot_ly(x = ~fecha) %>%
  add_trace(y = ~catch_1,
            type = "bar",
            color = paste0(desembarques_fabricas$id),
            marker = list(opacity = 0.5),
            name = paste0(desembarques_fabricas$id))%>%
  layout(barmode = "stack", 
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(desembarques_fabricas$fecha, na.rm = TRUE)-1,max(desembarques_fabricas$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Desembarques (t)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(current_temp$captura, na.rm = TRUE)*1.2)
  ),
  legend = list(font = list(size = params$legend_size - 2), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)', 
                orientation = "h")
)





```


<!-- # Plot Acumulados{data-orientation=rows data-navmenu="DESEMBARQUES"} -->

Rows
-------------------------------------

###
```{r, fig.width=4, fig.height=5}

if(!is.null(params$temporada_2)){

desembarques_acumulativos = merge(current_temp %>% dplyr::select(fecha, captura) %>% rlang::set_names(.,c("fecha","cap_temp_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(captura) %>% rlang::set_names(.,c("cap_temp_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE) %>%
  mutate(cumsum_1 = cumsumNA(cap_temp_1), cumsum_2 = cumsumNA(cap_temp_2))



fig_acum = desembarques_acumulativos %>% 
  plot_ly(x = ~fecha) %>%
  add_trace(y = ~cumsum_1,
            type = 'scatter', 
            mode = 'lines+markers',
            color = I('dodgerblue'), 
            name = paste0(params$temporada),
            marker = list(opacity = 0.5)) %>%
  add_trace(y = ~cumsum_2,
            type = 'scatter', 
            mode = 'lines+markers',
            color = I('orange'), 
            name = paste0(params$temporada_2), 
            marker = list(opacity = 0.5)) %>%
  layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(desembarques_acumulativos$fecha, na.rm = TRUE)-1,max(desembarques_acumulativos$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Desembarques acumulados (t)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(desembarques_acumulativos$cumsum_1, desembarques_acumulativos$cumsum_2), na.rm = TRUE)*1.3)
  ),
  legend = list(font = list(size = params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else {

  desembarques_acumulativos = current_temp %>% dplyr::select(fecha, captura) %>% rlang::set_names(.,c("fecha","cap_temp_1")) %>%
  mutate(cumsum_1 = cumsumNA(cap_temp_1))



fig_acum = desembarques_acumulativos %>% 
  plot_ly(x = ~fecha) %>%
  add_trace(y = ~cumsum_1,
            type = 'scatter', 
            mode = 'lines+markers',
            color = I('dodgerblue'), 
            name = paste0(params$temporada),
            marker = list(opacity = 0.5)) %>%
  layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(desembarques_acumulativos$fecha, na.rm = TRUE)-1,max(desembarques_acumulativos$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Desembarques acumulados (t)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(desembarques_acumulativos$cumsum_1), na.rm = TRUE)*1.3)
  ),
  legend = list(font = list(size = params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

}

fig_acum

```


###
```{r, fig.width=4, fig.height=5}

desembarques_fabricas_acumulados = current_temp %>% 
  dplyr::select(fecha, captura_AUSTRAL, captura_CAPRICORNIO, captura_CENTINELA, captura_CFG, captura_DIAMANTE, captura_EXALMAR, captura_HAYDUK, captura_TASA) %>% 
  dplyr::mutate(dia = 1:n()) %>% 
  pivot_longer(., cols = 2:9, names_to = c("empresa"), values_to = "catch_1")  %>%
  mutate(id = gsub("captura_", "",empresa))  %>% arrange(fecha) %>% group_by(id) %>% mutate(cumsum_1 = cumsumNA(catch_1))


desembarques_fabricas_acumulados %>%
   mutate(across(where(is.numeric), ~na_if(., 0))) %>% arrange(fecha) %>% 
  plot_ly(x = ~fecha) %>%
  add_trace(y = ~cumsum_1,
            type = "scatter",
            mode = 'lines+markers', 
            color = paste0(desembarques_fabricas_acumulados$id),
            marker = list(opacity = 0.5),
            name = paste0(desembarques_fabricas_acumulados$id)) %>%
  layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(desembarques_fabricas_acumulados$fecha, na.rm = TRUE)-1,max(desembarques_fabricas_acumulados$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Desembarques acumulados (t)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(desembarques_fabricas_acumulados$cumsum_1, na.rm = TRUE)*1.2)
  ),
  legend = list(font = list(size = params$legend_size - 2), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)', 
                orientation = "h")
)



```



# Descarga Data{data-navmenu="DESEMBARQUES"}

Rows
-------------------------------------
### 
```{r}

current_temp %>% select(temporada, fecha, captura, viajes) %>%
  mutate(captura_acumulada = cumsumNA(captura)) %>% set_names(.,c("temporada","fecha", "desembarque", "viajes","desembarque_acumulado"))%>%
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

###

```{r}

if(!is.null(params$temporada_2)){
  
current_temp_2 %>% select(temporada, fecha, captura, viajes) %>%
  mutate(captura_acumulada = cumsumNA(captura)) %>% set_names(.,c("temporada","fecha", "desembarque", "viajes","desembarque_acumulado"))%>%
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
}
```


# Plot{data-orientation=rows data-navmenu="ESFUERZO"}


Column
-------------------------------------

### 
```{r, fig.width=4, fig.height=3}
## ESFUERZO DURACION

if(!is.null(params$temporada_2)){
  
esfuerzo_duracion = merge(current_temp %>% dplyr::select(fecha, duracion) %>% rlang::set_names(.,c("fecha","dur_temp_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(duracion) %>% rlang::set_names(.,c("dur_temp_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)


fig3 <- plot_ly(esfuerzo_duracion) %>%
  add_trace(x = ~fecha, y = ~dur_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_esfuerzo), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada))%>%
  add_trace(x = ~fecha, y = ~dur_temp_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_esfuerzo_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2))%>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(esfuerzo_duracion$fecha, na.rm = TRUE)-1,max(esfuerzo_duracion$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Duración (h)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(esfuerzo_duracion$dur_temp_1, esfuerzo_duracion$dur_temp_2), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(size = params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else {
  
  esfuerzo_duracion = current_temp %>% dplyr::select(fecha, duracion) %>% rlang::set_names(.,c("fecha","dur_temp_1")) 


fig3 <- plot_ly(esfuerzo_duracion) %>%
  add_trace(x = ~fecha, y = ~dur_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_esfuerzo), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(esfuerzo_duracion$fecha, na.rm = TRUE)-1,max(esfuerzo_duracion$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Duración (h)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(esfuerzo_duracion$dur_temp_1), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(size = params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

  
}



fig3

```


###

```{r, fig.width=4, fig.height=3}
## ESFUERZO BODEGA

if(!is.null(params$temporada_2)){
  
esfuerzo_bodega = merge(current_temp %>% dplyr::mutate(bodega_mean = bodega/viajes) %>% dplyr::select(fecha, bodega_mean) %>% rlang::set_names(.,c("fecha","bodega_mean_temp_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::mutate(bodega_mean = bodega/viajes) %>% dplyr::select(bodega_mean) %>% rlang::set_names(.,c("bodega_mean_temp_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)


fig5 <- plot_ly(esfuerzo_bodega) %>%
  add_trace(x = ~fecha, y = ~bodega_mean_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_esfuerzo), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
  add_trace(x = ~fecha, y = ~bodega_mean_temp_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_esfuerzo_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2))%>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(esfuerzo_bodega$fecha, na.rm = TRUE)-1,max(esfuerzo_bodega$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Bodega (m^3)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0,  max(c(esfuerzo_bodega$bodega_mean_temp_1,esfuerzo_bodega$bodega_mean_temp_2), na.rm = TRUE)*1.2)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else {
  
  esfuerzo_bodega =current_temp %>% dplyr::mutate(bodega_mean = bodega/viajes) %>% dplyr::select(fecha, bodega_mean) %>% rlang::set_names(.,c("fecha","bodega_mean_temp_1"))


fig5 <- plot_ly(esfuerzo_bodega) %>%
  add_trace(x = ~fecha, y = ~bodega_mean_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_esfuerzo), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(esfuerzo_bodega$fecha, na.rm = TRUE)-1,max(esfuerzo_bodega$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Bodega (m^3)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0,  max(c(esfuerzo_bodega$bodega_mean_temp_1), na.rm = TRUE)*1.2)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

  
}

fig5

```


Row
-------------------------------------

###
```{r, fig.width=4, fig.height=3}
## ESFUERZO RECORRIDO

if(!is.null(params$temporada_2)){
  
esfuerzo_recorrido = merge(current_temp %>% dplyr::select(fecha, recorrido_medio) %>% rlang::set_names(.,c("fecha","recorrido_temp_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(recorrido_medio) %>% rlang::set_names(.,c("recorrido_temp_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)



fig7 <- plot_ly(esfuerzo_recorrido) %>%
  add_trace(x = ~fecha, y = ~recorrido_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_esfuerzo), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
  add_trace(x = ~fecha, y = ~recorrido_temp_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_esfuerzo_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(esfuerzo_recorrido$fecha, na.rm = TRUE)-1,max(esfuerzo_recorrido$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Recorrido (mn)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(esfuerzo_recorrido$recorrido_temp_1,esfuerzo_recorrido$recorrido_temp_2), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else {
  
  esfuerzo_recorrido = current_temp %>% dplyr::select(fecha, recorrido_medio) %>% rlang::set_names(.,c("fecha","recorrido_temp_1")) 


fig7 <- plot_ly(esfuerzo_recorrido) %>%
  add_trace(x = ~fecha, y = ~recorrido_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_esfuerzo), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(esfuerzo_recorrido$fecha, na.rm = TRUE)-1,max(esfuerzo_recorrido$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Recorrido (mn)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(esfuerzo_recorrido$recorrido_temp_1), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
  
}

fig7


```



### 
```{r, fig.width=4, fig.height=3}
## ESFUERZO LANCE

if(!is.null(params$temporada_2)){
  
esfuerzo_lance = merge(current_temp %>% dplyr::select(fecha, lances) %>% rlang::set_names(.,c("fecha","lances_temp_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(lances) %>% rlang::set_names(.,c("lances_temp_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)



fig9 <- plot_ly(esfuerzo_lance) %>%
  add_trace(x = ~fecha, y = ~lances_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_esfuerzo), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
  add_trace(x = ~fecha, y = ~lances_temp_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_esfuerzo_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(esfuerzo_lance$fecha, na.rm = TRUE)-1,max(esfuerzo_lance$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Lances", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(esfuerzo_lance$lances_temp_1,esfuerzo_lance$lances_temp_2), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else {
  
  esfuerzo_lance = current_temp %>% dplyr::select(fecha, lances) %>% rlang::set_names(.,c("fecha","lances_temp_1")) 


fig9 <- plot_ly(esfuerzo_lance) %>%
  add_trace(x = ~fecha, y = ~lances_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_esfuerzo), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(esfuerzo_lance$fecha, na.rm = TRUE)-1,max(esfuerzo_lance$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Lances", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(esfuerzo_lance$lances_temp_1), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
  
}

fig9

```

# Descarga Data{data-navmenu="ESFUERZO"}

Rows
-------------------------------------
### 
```{r}

current_temp %>% mutate(bodega_media = round(bodega/viajes, params$n_decimales), 
                        duracion = round(duracion, params$n_decimales), 
                        recorrio_medio  = round(recorrido_medio, params$n_decimales), 
                        lances = round(lances, params$n_decimales)) %>% 
  select(temporada, fecha, duracion, bodega_media, recorrio_medio, lances) %>% 
  set_names(., c("temporada","fecha","duracion","bodega","recorrido medio", "lances")) %>%
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

```

###

```{r}

if(!is.null(params$temporada_2)){
  
current_temp_2 %>% mutate(bodega_media = round(bodega/viajes, params$n_decimales), 
                          duracion = round(duracion, params$n_decimales), 
                          recorrio_medio  = round(recorrido_medio, params$n_decimales), 
                          lances = round(lances, params$n_decimales)) %>% 
  select(temporada, fecha, duracion, bodega_media, recorrio_medio, lances) %>% 
  set_names(., c("temporada","fecha","duracion","bodega","recorrido medio", "lances")) %>%
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
}
```




#  Plot{data-orientation=rows data-navmenu="CPUE"}


Row
-------------------------------------

###
```{r, fig.width=4, fig.height=3}

## CPUE DURACION

if(!is.null(params$temporada_2)){
  
cpue_duracion = merge(current_temp %>% dplyr::select(fecha, cpue_dur) %>% rlang::set_names(.,c("fecha","cpue_dur_temp_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(cpue_dur) %>% rlang::set_names(.,c("cpue_dur_temp_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)


fig4 <- plot_ly(cpue_duracion) %>%
  add_trace(x = ~fecha, y = ~cpue_dur_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_cpue), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
  add_trace(x = ~fecha, y = ~cpue_dur_temp_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_cpue_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2))%>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(cpue_duracion$fecha, na.rm = TRUE)-1,max(cpue_duracion$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "CPUE (t/h)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(cpue_duracion$cpue_dur_temp_1,cpue_duracion$cpue_dur_temp_2), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else {
  
  cpue_duracion = current_temp %>% dplyr::select(fecha, cpue_dur) %>% rlang::set_names(.,c("fecha","cpue_dur_temp_1")) 


fig4 <- plot_ly(cpue_duracion) %>%
  add_trace(x = ~fecha, y = ~cpue_dur_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_cpue), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(cpue_duracion$fecha, na.rm = TRUE)-1,max(cpue_duracion$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "CPUE (t/h)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(cpue_duracion$cpue_dur_temp_1), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
  
}


fig4

```

###
```{r, fig.width=4, fig.height=3}

## CPUE BODEGA

if(!is.null(params$temporada_2)){
  
cpue_bodega = merge(current_temp %>% dplyr::select(fecha, cpue_bod) %>% rlang::set_names(.,c("fecha","cpue_bod_temp_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(cpue_bod) %>% rlang::set_names(.,c("cpue_bod_temp_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)



fig6 <- plot_ly(cpue_bodega) %>%
  add_trace(x = ~fecha, y = ~cpue_bod_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_cpue), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
  add_trace(x = ~fecha, y = ~cpue_bod_temp_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_cpue_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2))%>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(cpue_bodega$fecha, na.rm = TRUE)-1,max(cpue_bodega$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "CPUE (t/m^3)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(cpue_bodega$cpue_bod_temp_1,cpue_bodega$cpue_bod_temp_2), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
} else {
  
cpue_bodega = current_temp %>% dplyr::select(fecha, cpue_bod) %>% rlang::set_names(.,c("fecha","cpue_bod_temp_1")) %>% dplyr::mutate(dia = 1:n())



fig6 <- plot_ly(cpue_bodega) %>%
  add_trace(x = ~fecha, y = ~cpue_bod_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_cpue), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(cpue_bodega$fecha, na.rm = TRUE)-1,max(cpue_bodega$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "CPUE (t/m^3)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(cpue_bodega$cpue_bod_temp_1, na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)  
  
}

fig6

```

Column
-------------------------------------

###
```{r, fig.width=4, fig.height=3}

## CPUE RECORRIDO

if(!is.null(params$temporada_2)){
  
cpue_rec = merge(current_temp %>% dplyr::select(fecha, cpue_rec) %>% rlang::set_names(.,c("fecha","cpue_rec_temp_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(cpue_rec) %>% rlang::set_names(.,c("cpue_rec_temp_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)


fig8 <- plot_ly(cpue_rec) %>%
  add_trace(x = ~fecha, y = ~cpue_rec_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_cpue), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
  add_trace(x = ~fecha, y = ~cpue_rec_temp_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_cpue_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(cpue_rec$fecha, na.rm = TRUE)-1,max(cpue_rec$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "CPUE (t/mn)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(cpue_rec$cpue_rec_temp_1,cpue_rec$cpue_rec_temp_2), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
} else {
  
  cpue_rec = current_temp %>% dplyr::select(fecha, cpue_rec) %>% rlang::set_names(.,c("fecha","cpue_rec_temp_1"))


fig8 <- plot_ly(cpue_rec) %>%
  add_trace(x = ~fecha, y = ~cpue_rec_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_cpue), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(cpue_rec$fecha, na.rm = TRUE)-1,max(cpue_rec$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "CPUE (t/mn)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(cpue_rec$cpue_rec_temp_1), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
  
}

fig8

```

###
```{r, fig.width=4, fig.height=3}

## CPUE LANCE

if(!is.null(params$temporada_2)){
  
cpue_lance = merge(current_temp %>% dplyr::select(fecha, cpue_lan) %>% rlang::set_names(.,c("fecha","cpue_lan_temp_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(cpue_lan) %>% rlang::set_names(.,c("cpue_lan_temp_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)



fig10 <- plot_ly(cpue_lance) %>%
  add_trace(x = ~fecha, y = ~cpue_lan_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_cpue), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada))  %>%
  add_trace(x = ~fecha, y = ~cpue_lan_temp_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_cpue_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(cpue_lance$fecha, na.rm = TRUE)-1,max(cpue_lance$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "CPUE (t/lance)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(cpue_lance$cpue_lan_temp_1,cpue_lance$cpue_lan_temp_2), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
} else{
  
  cpue_lance = current_temp %>% dplyr::select(fecha, cpue_lan) %>% rlang::set_names(.,c("fecha","cpue_lan_temp_1")) %>% dplyr::mutate(dia = 1:n())



fig10 <- plot_ly(cpue_lance) %>%
  add_trace(x = ~fecha, y = ~cpue_lan_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_cpue), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(cpue_lance$fecha, na.rm = TRUE)-1,max(cpue_lance$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "CPUE (t/lance)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(cpue_lance$cpue_lan_temp_1), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
  
}

fig10

```



#  Descarga Data{data-navmenu="CPUE"}

Rows
-------------------------------------

###
```{r}

current_temp %>% mutate(cpue_dur = round(cpue_dur, params$n_decimales), 
                        cpue_lan = round(cpue_lan, params$n_decimales), 
                        cpue_rec = round(cpue_rec, params$n_decimales), 
                        cpue_bod = round(cpue_bod, params$n_decimales)) %>% 
  select(temporada, fecha, cpue_dur, cpue_lan, cpue_rec, cpue_bod) %>%
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


```

###
```{r}

if(!is.null(params$temporada_2)){
  
current_temp_2 %>% mutate(cpue_dur = round(cpue_dur, params$n_decimales), 
                          cpue_lan = round(cpue_lan, params$n_decimales), 
                          cpue_rec = round(cpue_rec, params$n_decimales), 
                          cpue_bod = round(cpue_bod, params$n_decimales)) %>% 
  select(temporada, fecha, cpue_dur, cpue_lan, cpue_rec, cpue_bod) %>%
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

}
```


#  Plot{data-orientation=rows data-navmenu="INDICADORES ESPACIALES"}


Row
-------------------------------------
###
```{r, fig.width=4, fig.height=3}

if(!is.null(params$temporada_2)){
  
indi_area = merge(current_temp %>% dplyr::select(fecha, area_pesca) %>% rlang::set_names(.,c("fecha","area_temp_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(area_pesca) %>% rlang::set_names(.,c("area_temp_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)



fig11 <- plot_ly(indi_area) %>%
  add_trace(x = ~fecha, y = ~area_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
  add_trace(x = ~fecha, y = ~area_temp_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_area$fecha, na.rm = TRUE)-1,max(indi_area$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Área Pesca (mn^2)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(indi_area$area_temp_1,indi_area$area_temp_2), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else {
  
  indi_area = current_temp %>% dplyr::select(fecha, area_pesca) %>% rlang::set_names(.,c("fecha","area_temp_1")) 


fig11 <- plot_ly(indi_area) %>%
  add_trace(x = ~fecha, y = ~area_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_area$fecha, na.rm = TRUE)-1,max(indi_area$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Área Pesca (mn^2)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(indi_area$area_temp_1), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
  
}

fig11

```

###
```{r, fig.width=4, fig.height=4}

if(!is.null(params$temporada_2)){
  
indi_inercia = merge(current_temp %>% dplyr::select(fecha, inercia_espacial) %>% rlang::set_names(.,c("fecha","inercia_espacial_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(inercia_espacial) %>% rlang::set_names(.,c("inercia_espacial_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)


fig16 <- plot_ly(indi_inercia) %>%
  add_trace(x = ~fecha, y = ~inercia_espacial_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>% 
  add_trace(x = ~fecha, y = ~inercia_espacial_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_inercia$fecha, na.rm = TRUE)-1,max(indi_inercia$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Inercia Espacial", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(indi_inercia$inercia_espacial_1, indi_inercia$inercia_espacial_2), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else {
  
  indi_inercia = current_temp %>% dplyr::select(fecha, inercia_espacial) %>% rlang::set_names(.,c("fecha","inercia_espacial_1")) 


fig16 <- plot_ly(indi_inercia) %>%
  add_trace(x = ~fecha, y = ~inercia_espacial_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_inercia$fecha, na.rm = TRUE)-1,max(indi_inercia$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Inercia Espacial", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(indi_inercia$inercia_espacial_1), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
  
}

fig16

```

Row
-------------------------------------

###
```{r, fig.width=4, fig.height=3}

if(!is.null(params$temporada_2)){
  
indi_latitud = merge(current_temp %>% dplyr::select(fecha, latitud) %>% rlang::set_names(.,c("fecha","lat_med_temp_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(latitud) %>% rlang::set_names(.,c("lat_med_temp_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)


fig_lat = plot_ly(indi_latitud)%>%
  add_trace(x = ~fecha, y = ~lat_med_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.3), name = paste0(params$temporada)) %>%
  add_trace(x = ~fecha, y = ~lat_med_temp_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_latitud$fecha, na.rm = TRUE)-1,max(indi_latitud$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 12),
      title = list(text = "Latitud (°S)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(-18,0)
      
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else {
  
  indi_latitud = current_temp %>% dplyr::select(fecha, latitud) %>% rlang::set_names(.,c("fecha","lat_med_temp_1"))

fig_lat = plot_ly(indi_latitud)%>%
  add_trace(x = ~fecha, y = ~lat_med_temp_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.3), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_latitud$fecha, na.rm = TRUE)-1,max(indi_latitud$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 12),
      title = list(text = "Latitud (°S)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(-18,0)
      
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
  
  
}

fig_lat

```

###
```{r, fig.width=4, fig.height=3}

if(!is.null(params$temporada_2)){
  
indi_latitud_max_min = merge(current_temp %>% dplyr::select(fecha, cala_latitud_maxima, cala_latitud_min) %>% rlang::set_names(.,c("fecha","lat_max_temp_1","lat_min_temp_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(cala_latitud_maxima, cala_latitud_min) %>% rlang::set_names(.,c("lat_max_temp_2","lat_min_temp_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)


fig_lat_max_min = plot_ly(indi_latitud_max_min) %>%
  add_segments(x = ~fecha, xend = ~fecha, y = ~lat_max_temp_1, yend = ~lat_min_temp_1, color =  I(params$color_indicadores), legendgroup =params$temporada, name = paste0(params$temporada)) %>% 
  add_markers(x = ~fecha, y = ~lat_max_temp_1, color =  I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.5), legendgroup=params$temporada, showlegend = FALSE) %>%
  add_markers(x = ~fecha, y = ~lat_min_temp_1, color =  I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.5), legendgroup=params$temporada, showlegend = FALSE) %>%
  add_segments(x = ~fecha, xend = ~fecha, y = ~lat_max_temp_2, yend = ~lat_min_temp_2, color =  I(params$color_indicadores_2), legendgroup=params$temporada_2, name = paste0(params$temporada_2)) %>% 
  add_markers(x = ~fecha, y = ~lat_max_temp_2, color =  I(params$color_indicadores_2), marker = list(size = params$marker_size, opacity = 0.5), legendgroup=params$temporada_2, showlegend = FALSE) %>%
  add_markers(x = ~fecha, y = ~lat_min_temp_2, color =  I(params$color_indicadores_2), marker = list(size = params$marker_size, opacity = 0.5), legendgroup= params$temporada_2, showlegend = FALSE) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_latitud_max_min$fecha, na.rm = TRUE)-1,max(indi_latitud_max_min$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 12),
      title = list(text = "Rango Latitud (°S)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(-18,0)
      
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else {
  
  indi_latitud_max_min = current_temp %>% dplyr::select(fecha, cala_latitud_maxima, cala_latitud_min) %>% rlang::set_names(.,c("fecha","lat_max_temp_1","lat_min_temp_1")) 


fig_lat_max_min = plot_ly(indi_latitud_max_min) %>%
  add_segments(x = ~fecha, xend = ~fecha, y = ~lat_max_temp_1, yend = ~lat_min_temp_1, color =  I(params$color_indicadores), legendgroup =params$temporada, name = paste0(params$temporada)) %>% 
  add_markers(x = ~fecha, y = ~lat_max_temp_1, color =  I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.5), legendgroup=params$temporada, showlegend = FALSE) %>%
  add_markers(x = ~fecha, y = ~lat_min_temp_1, color =  I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.5), legendgroup=params$temporada, showlegend = FALSE)  %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_latitud_max_min$fecha, na.rm = TRUE)-1,max(indi_latitud_max_min$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 12),
      title = list(text = "Rango Latitud (°S)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(-18,0)
      
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

  
}

fig_lat_max_min

```

Row
-------------------------------------


###
```{r, fig.width=4, fig.height=4}

if(!is.null(params$temporada_2)){
  
indi_distancia = merge(current_temp %>% dplyr::select(fecha, dist_maxima_zarpe, dist_costa, dist_maxima_arribo) %>% rlang::set_names(.,c("fecha","dist_max_zarpe_1","dist_costa_1","dist_max_aribo_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(dist_maxima_zarpe, dist_costa, dist_maxima_arribo) %>% rlang::set_names(.,c("dist_max_zarpe_2","dist_costa_2","dist_max_aribo_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)


fig_dist = plot_ly(indi_distancia) %>%
  add_trace(x = ~fecha, y = ~dist_costa_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.3), name = paste0(params$temporada)) %>%
  add_trace(x = ~fecha, y = ~dist_costa_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_distancia$fecha, na.rm = TRUE)-1,max(indi_distancia$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Distancia Costa (mn)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(indi_distancia$dist_costa_1, indi_distancia$dist_costa_2), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else { 
  
indi_distancia = current_temp %>% dplyr::select(fecha, dist_maxima_zarpe, dist_costa, dist_maxima_arribo) %>% rlang::set_names(.,c("fecha","dist_max_zarpe_1","dist_costa_1","dist_max_aribo_1")) 

fig_dist = plot_ly(indi_distancia) %>%
  add_trace(x = ~fecha, y = ~dist_costa_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.3), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_distancia$fecha, na.rm = TRUE)-1,max(indi_distancia$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Distancia Costa (mn)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(indi_distancia$dist_costa_1), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
    
}

fig_dist

```


###
```{r, fig.width=4, fig.height=4}

if(!is.null(params$temporada_2)){
  
indi_distancia = merge(current_temp %>% dplyr::select(fecha, dist_maxima_zarpe, dist_costa, dist_maxima_arribo) %>% rlang::set_names(.,c("fecha","dist_max_zarpe_1","dist_costa_1","dist_max_aribo_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(dist_maxima_zarpe, dist_costa, dist_maxima_arribo) %>% rlang::set_names(.,c("dist_max_zarpe_2","dist_costa_2","dist_max_aribo_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)


fig_dist_zarpe = plot_ly(indi_distancia) %>%
  add_trace(x = ~fecha, y = ~dist_max_zarpe_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
  add_trace(x = ~fecha, y = ~dist_max_zarpe_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_distancia$fecha, na.rm = TRUE)-1,max(indi_distancia$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Distancia máxima zarpe (mn)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(indi_distancia$dist_max_zarpe_1, indi_distancia$dist_costa_1, indi_distancia$dist_max_aribo_1, indi_distancia$dist_max_zarpe_2, indi_distancia$dist_costa_2, indi_distancia$dist_max_aribo_2), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else {
  
    
indi_distancia = current_temp %>% dplyr::select(fecha, dist_maxima_zarpe, dist_costa, dist_maxima_arribo) %>% rlang::set_names(.,c("fecha","dist_max_zarpe_1","dist_costa_1","dist_max_aribo_1"))


fig_dist_zarpe = plot_ly(indi_distancia) %>%
  add_trace(x = ~fecha, y = ~dist_max_zarpe_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_distancia$fecha, na.rm = TRUE)-1,max(indi_distancia$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Distancia máxima zarpe (mn)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(indi_distancia$dist_max_zarpe_1, indi_distancia$dist_costa_1, indi_distancia$dist_max_aribo_1), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
  
}

fig_dist_zarpe

```
Row
-------------------------------------

###
```{r, fig.width=4, fig.height=4}

if(!is.null(params$temporada_2)){
  
indi_distancia = merge(current_temp %>% dplyr::select(fecha, dist_maxima_zarpe, dist_costa, dist_maxima_arribo) %>% rlang::set_names(.,c("fecha","dist_max_zarpe_1","dist_costa_1","dist_max_aribo_1")) %>% dplyr::mutate(dia = 1:n()),
                     current_temp_2 %>% dplyr::select(dist_maxima_zarpe, dist_costa, dist_maxima_arribo) %>% rlang::set_names(.,c("dist_max_zarpe_2","dist_costa_2","dist_max_aribo_2")) %>% dplyr::mutate(dia = 1:n()), by = "dia", all = TRUE)


fig_dist_arribo = plot_ly(indi_distancia) %>% 
  add_trace(x = ~fecha, y = ~dist_max_aribo_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>% 
  add_trace(x = ~fecha, y = ~dist_max_aribo_2, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores_2), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada_2)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_distancia$fecha, na.rm = TRUE)-1,max(indi_distancia$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Distancia máxima arribo (mn)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(indi_distancia$dist_max_zarpe_1, indi_distancia$dist_costa_1, indi_distancia$dist_max_aribo_1, indi_distancia$dist_max_zarpe_2, indi_distancia$dist_costa_2, indi_distancia$dist_max_aribo_2), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)

} else {
  
  indi_distancia = current_temp %>% dplyr::select(fecha, dist_maxima_zarpe, dist_costa, dist_maxima_arribo) %>% rlang::set_names(.,c("fecha","dist_max_zarpe_1","dist_costa_1","dist_max_aribo_1")) 


fig_dist_arribo = plot_ly(indi_distancia) %>% 
  add_trace(x = ~fecha, y = ~dist_max_aribo_1, type = 'scatter', mode = 'lines+markers', color = I(params$color_indicadores), marker = list(size = params$marker_size, opacity = 0.5), name = paste0(params$temporada)) %>%
 layout(  
    xaxis = list(
      type = 'date',
      tickformat = "%d-%m-%Y", 
      autotick = F, 
      dtick = 86400000*params$paso_dias,
      tickangle = 270,
      tickfont = list(family='Rockwell', color='black', size = 18),
      title = F,
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      range = c(min(indi_distancia$fecha, na.rm = TRUE)-1,max(indi_distancia$fecha, na.rm = TRUE)+1)), 
    yaxis = list(
      tickfont = list(color='black', size = 16),
      title = list(text = "Distancia máxima arribo (mn)", font = list(size = 20)),
      showline = TRUE,
      mirror = "ticks",
      linecolor = toRGB("black"),
      linewidth = 2,
      ticks = "outside", 
      range = c(0, max(c(indi_distancia$dist_max_zarpe_1, indi_distancia$dist_costa_1, indi_distancia$dist_max_aribo_1), na.rm = TRUE)*1.4)
  ),
  legend = list(font = list(params$legend_size), 
                xanchor = "left", 
                yanchor = "top", 
                x = 0.01, 
                y = 0.99, 
                bgcolor = 'rgba(0,0,0,0)')
)
  
}

fig_dist_arribo


```

### 
```{r, fig.width=4, fig.height=4}
```
#  Descarga Data{data-navmenu="INDICADORES ESPACIALES"}

Rows
-------------------------------------

###
```{r}
current_temp %>% mutate(area_pesca = round(area_pesca, params$n_decimales),
                        inercia = round(inercia_espacial, params$n_decimales),
                        latitud = round(latitud, params$n_decimales), 
                        latitud_maxima = round(cala_latitud_maxima, params$n_decimales),
                        latitud_minima = round(cala_latitud_min, params$n_decimales),
                        dist_costa = round(dist_costa, params$n_decimales), 
                        dist_maxima_zarpe = round(dist_maxima_zarpe, params$n_decimales),
                        dist_maxima_arribo = round(dist_maxima_arribo, params$n_decimales)) %>%
  select(temporada, fecha, area_pesca, inercia, latitud, latitud_maxima, latitud_minima, dist_costa, dist_maxima_zarpe, dist_maxima_arribo) %>%
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))


```


###
```{r}

if(!is.null(params$temporada_2)){
  
current_temp_2 %>% mutate(area_pesca = round(area_pesca, params$n_decimales),
                        inercia = round(inercia_espacial, params$n_decimales),
                        latitud = round(latitud, params$n_decimales), 
                        latitud_maxima = round(cala_latitud_maxima, params$n_decimales),
                        latitud_minima = round(cala_latitud_min, params$n_decimales),
                        dist_costa = round(dist_costa, params$n_decimales), 
                        dist_maxima_zarpe = round(dist_maxima_zarpe, params$n_decimales),
                        dist_maxima_arribo = round(dist_maxima_arribo, params$n_decimales)) %>%
  select(temporada, fecha, area_pesca, inercia, latitud, latitud_maxima, latitud_minima, dist_costa, dist_maxima_zarpe, dist_maxima_arribo) %>%
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))

}
```




#  Mapa Fijo{data-orientation=rows data-navmenu="MAPAS CALAS"}


Row
-------------------------------------

###
```{r, fig.width=6, fig.height=6}

mapa_calas = current_calas
par(mar = c(3,3,1,1))
plot_peru(ylim = c(-19,-3), area_iso = params$areas, font_harbor = 11, land.col = "peru")
points(x = mapa_calas$longitud, y = mapa_calas$latitud, pch = 19, cex = 0.5, col = alpha("black", 0.4))
mtext(text = "Calas - Temporada", side = 3)

# lines(x = lineaParela$l60$lon,lineaParela$l60$lat, lwd = 1, col = "brown")


```


###
```{r, fig.width=6, fig.height=6}
par(mar = c(3,3,1,1))
mapa_last_day = current_calas %>% filter(fecha %in% max(fecha))
plot_peru(ylim = c(-19,-3), area_iso = params$areas, font_harbor = 11, land.col = "peru")
points(x = mapa_last_day$longitud, y = mapa_last_day$latitud, pch = 19, cex = 0.8, col = alpha("red",0.4))

mtext(text = unique(mapa_last_day$fecha), side = 3)

```



#  Mapa Interactivo {data-orientation=rows data-navmenu="MAPAS CALAS"}

Column
-------------------------------------
###
```{r, fig.width=9, fig.height=10}

mapa_calas = current_calas

map_fig <- mapa_calas %>%
  mutate(color = factor(ifelse(fecha %in% max(fecha), as.character(max(fecha)),"Total"), levels = c("Total",as.character(max(fecha))))) %>%
  plot_ly(
    lat = ~latitud,
    lon = ~longitud,
    mode = "markers",
    color = ~color,
    colors = c("gray2","tomato3"),
    marker = list(size = 12, opacity = 0.6),
    type = 'scattermapbox',
    hovertext = ~paste(paste("Fecha:",mapa_calas[,"fecha"]),
                       paste("embarcación:",mapa_calas[,"embarcacion"]),
                       paste("Capt.:",mapa_calas[,"declarado_tm"]," t"),
                       paste("%Juv:",mapa_calas[,"porcentaje_juvenil"]),
                       paste("D.Costa:",mapa_calas[,"dc"], " mn"), sep = "<br />"))


map_fig <- map_fig %>%
  layout(
    mapbox = list(
      style = 'open-street-map',
      zoom = 5,
      center = list(lon = -75, lat = -10),
  legend = list(font = list(size = 30)))
  )


map_fig
```


#  Mapa Fijo {data-orientation=rows data-navmenu="MAPAS SISESAT"}


Row
-------------------------------------

###
```{r, fig.width=6, fig.height=6}


mapa_calas = current_trayectorias 

par(mar = c(3,3,1,1))

plot_peru(ylim = c(-19,-3), area_iso = params$areas, font_harbor = 11, land.col = "peru")

for(y in 1:length(unique(mapa_calas$Cod_Viaje_VMS))){
  
  tray_mapa = mapa_calas[mapa_calas$Cod_Viaje_VMS %in% unique(mapa_calas$Cod_Viaje_VMS)[y],]
  
  lines(x = tray_mapa$Lon, y = tray_mapa$Lat, lwd = 0.8)
  
}

# lines(x = lineaParela$l60$lon,lineaParela$l60$lat, lwd = 1, col = "brown")

mtext(text = "Trayectorias - Temporada", side = 3)

```

###
```{r, fig.width=6, fig.height=6}
id_viajes = current_trayectorias %>% filter(fecha %in% max(fecha)) %>% reframe(viajes = unique(Cod_Viaje_VMS))

mapa_last_day_tray = current_trayectorias %>% filter(Cod_Viaje_VMS %in% id_viajes$viajes) 

par(mar = c(3,3,1,1))
plot_peru(ylim = c(-19,-3), area_iso = params$areas, font_harbor = 11, land.col = "peru")

for(y in 1:length(unique(mapa_last_day_tray$Cod_Viaje_VMS))){
  
  lines(x = mapa_last_day_tray[mapa_last_day_tray$Cod_Viaje_VMS %in% unique(mapa_last_day_tray$Cod_Viaje_VMS)[y],]$Lon, y = mapa_last_day_tray[mapa_last_day_tray$Cod_Viaje_VMS %in% unique(mapa_last_day_tray$Cod_Viaje_VMS)[y],]$Lat, lwd = 0.8, col = "red")
  
}

mtext(text = max(unique(mapa_last_day_tray$fecha)), side = 3)

```

#  Mapa Interactivo {data-orientation=rows data-navmenu="MAPAS SISESAT"}


Column
-------------------------------------

###

```{r, fig.width=9, fig.height=10}

id_viajes = current_trayectorias %>% filter(fecha %in% max(fecha)) %>% reframe(viajes = unique(Cod_Viaje_VMS))


current_sisesat_plot = current_trayectorias %>% filter(Cod_Viaje_VMS %in% id_viajes$viajes)


map_fig2 <- current_sisesat_plot  %>%
  plot_ly(
    lat = ~Lat,
    lon = ~Lon,
    type = 'scattermapbox',
    mode = "lines+markers",
    split = ~Cod_Viaje_VMS,
    marker = list(color = ~Cod_Viaje_VMS,
                  colors = as.factor(ifelse(current_sisesat_plot$Vel.Cal < 5, "red","blue")),
                  size = 8,
                  opacity = 0.6),
    hovertext = ~paste(paste("Fecha Zarpe:",current_sisesat_plot$fecha_zarpe),
                       paste("Fecha Arribo:",current_sisesat_plot$fecha_arribo),
                       paste("Vel. Calculada:",current_sisesat_plot$Vel.Cal), sep = "<br />"))


map_fig2 <- map_fig2 %>%
  layout(
    mapbox = list(
      style = 'open-street-map',
      zoom = 5,
      center = list(lon = -75, lat = -10),
  legend = list(font = list(size = 30)))
  )


map_fig2




```






